### ISSUE TITLE
 KeyError: 'user'

### ISSUE THREAD

**Issue by VictorOwinoKe** [annu12340/DocAtHome#1]
How do I solve this, I am running into error while registering a new user
**Traceback (most recent call last)**
File "C:\Users\pc\Desktop\capstone\DocAtHome-master\DocEnv\Lib\site-packages\flask\app.py", line 2464, in __call__
return self.wsgi_app(environ, start_response)
File "C:\Users\pc\Desktop\capstone\DocAtHome-master\DocEnv\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
response = self.handle_exception(e)
File "C:\Users\pc\Desktop\capstone\DocAtHome-master\DocEnv\Lib\site-packages\flask\app.py", line 1867, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\Users\pc\Desktop\capstone\DocAtHome-master\DocEnv\Lib\site-packages\flask\_compat.py", line 39, in reraise
raise value
File "C:\Users\pc\Desktop\capstone\DocAtHome-master\DocEnv\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "C:\Users\pc\Desktop\capstone\DocAtHome-master\DocEnv\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Users\pc\Desktop\capstone\DocAtHome-master\DocEnv\Lib\site-packages\flask\app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\Users\pc\Desktop\capstone\DocAtHome-master\DocEnv\Lib\site-packages\flask\_compat.py", line 39, in reraise
raise value
File "C:\Users\pc\Desktop\capstone\DocAtHome-master\DocEnv\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "C:\Users\pc\Desktop\capstone\DocAtHome-master\DocEnv\Lib\site-packages\flask\app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
**File "C:\Users\pc\Desktop\capstone\DocAtHome-master\Main.py", line 131, in medical_register
user_id = session['user']**
File "C:\Users\pc\Desktop\capstone\DocAtHome-master\DocEnv\Lib\site-packages\werkzeug\local.py", line 377, in <lambda>
__getitem__ = lambda x, i: x._get_current_object()[i]
File "C:\Users\pc\Desktop\capstone\DocAtHome-master\DocEnv\Lib\site-packages\flask\sessions.py", line 84, in __getitem__
return super(SecureCookieSession, self).__getitem__(key)

**Comment by annu12340** [comment]
Could you share the screenshots of the registration pg with the details that you had entered

**Comment by VictorOwinoKe** [comment]
Is there any specific information to be entered ,,I just shared the above trace back call, Thta the error I get immediately I press Submit Button, Under user registration

**Comment by VictorOwinoKe** [comment]
////DocAtHome-master\Main.py", line 131, in medical_register
user_id = session['user']
That the line with the error , How do I go about it

**Comment by annu12340** [comment]
> Is there any specific information to be entered ,,I just shared the above trace back call, Thta the error I get immediately I press Submit Button, Under user registration

I haven't encountered such an error msg while I developing the product. That's why I asked 

> ////DocAtHome-master\Main.py", line 131, in medical_register
> user_id = session['user']
> That the line with the error , How do I go about it

Whenever a user successfully logins to the system, a new session would be created. This is done to distinguish between the contents to be shown by user A and another user B

So, here the issue errors while creating this session. I think the issue is occurs while logging in.
Were you able to register successfully?

**Comment by VictorOwinoKe** [comment]
![image](https://user-images.githubusercontent.com/56676033/96386732-bd694180-11a5-11eb-97ba-112023763138.png)

**********************
 I can not register any user successfully....
I get the error immediately I fill in this for and press submit...
************************* 
Can You whatsapp to help me
**** (My Whatsapp, +254726032764)****

**Comment by annu12340** [comment]
Try deleting the SQLite database and start over

**Comment by VictorOwinoKe** [comment]
I have deleted the db file and running the app a fresh... it creates the db but I still have the same issue

**Comment by VictorOwinoKe** [comment]
Can You add the requirements.txt file,

**Comment by VictorOwinoKe** [comment]
I realy need to run the app,,,still cant register a user after several attempts

**Comment by annu12340** [comment]
> Can You add the requirements.txt file,

I have added the requirements.txt file

**Comment by VictorOwinoKe** [comment]
I have tried my best, can you help me solve the problem at a cost

**Comment by VictorOwinoKe** [comment]
I installed the requirements.txt
deleted the sqlite and run the app
still getting the key value error  at line 131 of the main.py
................user_id = session['user'].......................

**Comment by VictorOwinoKe** [comment]
I am closing the issue since the problem still persist

**Comment by annu12340** [comment]
> I am closing the issue since the problem still persist

I am sorry for not being able to help

**Comment by VictorOwinoKe** [comment]
I still need your help, the error still persist

**Comment by VictorOwinoKe** [comment]
can You create a user then share the login with me, maybe am the one doing it the wrong way

**Comment by VictorOwinoKe** [comment]
I was trying to compare the code with the Menteor.me project on your repo,  I cant identify why we have the error

**Comment by VictorOwinoKe** [comment]
**### FOUND THE SOLUTION**
 I found the issue. You only create the user value in the session in your login route. In the register route, you redirect to the medical_register route, where you attempt to access session['user'], which doesn't exist.
t's super simple to correct it  . Just create the session before you redirect.
Right before line 124.

I also noticed you have different templates for error messages, such as incorrectLogin
Instead of having different templates for this, you should look into flash-messaging in flask.

That particular thing won't fix anything, but it will make your project cleaner and smaller

**Comment by annu12340** [comment]
> **### FOUND THE SOLUTION**
> I found the issue. You only create the user value in the session in your login route. In the register route, you redirect to the medical_register route, where you attempt to access session['user'], which doesn't exist.
> t's super simple to correct it . Just create the session before you redirect.
> Right before line 124.
> 
> I also noticed you have different templates for error messages, such as incorrectLogin
> Instead of having different templates for this, you should look into flash-messaging in flask.
> 
> That particular thing won't fix anything, but it will make your project cleaner and smaller

Thanks for the suggesting flash-messaging
